# Generated by Django 4.0.5 on 2022-06-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=30)),
                ('dish_desc', models.CharField(max_length=30)),
                ('dish_prise', models.IntegerField()),
                ('dish_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
