# Generated by Django 4.0.5 on 2022-06-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishes',
            old_name='dish_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='dishes',
            old_name='dish_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='dishes',
            old_name='dish_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='dishes',
            old_name='dish_prise',
            new_name='prise',
        ),
    ]
