# Generated by Django 4.0.5 on 2022-06-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_menu_review_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobileno', models.CharField(max_length=10)),
                ('food_name', models.CharField(max_length=20)),
                ('extra_food', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('address', models.TextField()),
                ('msg', models.TextField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='desc',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='prise',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='rev',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='search',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
