# Generated by Django 4.0.5 on 2022-06-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_order_menu_desc_menu_img_menu_name_menu_prise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialdish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
