# Generated by Django 4.0.5 on 2022-06-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_order_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobileno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
