# Generated by Django 4.0.5 on 2022-07-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_remove_review_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='code',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialdish',
            name='code',
            field=models.IntegerField(default=33),
            preserve_default=False,
        ),
    ]
