# Generated by Django 4.0.5 on 2022-07-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_login_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searchhhh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sear', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='search',
        ),
    ]
