# Generated by Django 4.0.5 on 2022-07-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_searchhhh_delete_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='prise',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialdish',
            name='prise',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
