# Generated by Django 4.0.5 on 2022-07-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_cart_prise_specialdish_prise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_token', models.IntegerField()),
            ],
        ),
    ]
