# Generated by Django 4.0.5 on 2022-07-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_login_active_seassion_signup_active_seassion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='c_k',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
