# Generated by Django 4.0.5 on 2022-07-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_login_c_k'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='active_seassion',
        ),
        migrations.RemoveField(
            model_name='login',
            name='c_k',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='active_seassion',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='c_k',
        ),
    ]
